### PR TITLE
Added annotation hints for every glyph in ANNOTATION_INFO

### PR DESCRIPTION
**Pull request by Cankyre**
https://github.com/franciscoBSalgueiro/en-croissant/assets/75273490/c9126f59-8743-4bae-bfd8-b238ec8a0cb9

### CODE REVIEW

**Comment by Cankyre** [comment]
Oh, sorry I missed that.

**Comment by Cankyre** [comment]
Fixed

**Comment by Cankyre** [comment]
In this case, only `!!` is shown
It's ordered via this code from `treeReducer.ts`, only the first one is shown:
```tsx
const newAnnotations = node.annotations.filter(
  (a) =>
    !ANNOTATION_INFO[a].group ||
    ANNOTATION_INFO[a].group !== ANNOTATION_INFO[payload].group,
);
node.annotations = [...newAnnotations, payload].sort((a, b) =>
  ANNOTATION_INFO[a].nag > ANNOTATION_INFO[b].nag ? 1 : -1,
);
```
The priority is defined by the nag in ANNOTATION_INFO (utils/annotation.ts)

**Comment by franciscoBSalgueiro** [comment]
Thank you!

**Pull request merged**
