### PR TITLE
Updated readme to include contribution instructions

### PR DESCRIPTION
**Pull request by yuval59**

### CODE REVIEW

**Comment by yuval59** [comment]
Thank god

Sorry if you got spammed with notifications because I apparently suck at using Git

**Comment by yuval59** [comment]
Yeah, I was also unsure about that
Whatever you feel like doing. Should I move it?

**Comment by yuval59** [comment]
Ok done
And I also changed the commands to be more specific so you can now just use `pnpm build` instead of writing the whole `pnpm tauri build -b none` thing
This does not break the previous ones, if you still wanna write the whole thing you can

**Comment by franciscoBSalgueiro** [comment]
I didn't write `pnpm tauri build -b none` for no reason. On windows (and maybe Mac idk), if you don't have the private key, building with bundle will fail with an error. Even if it didn't, if you're building from source, it makes no sense to also make the bundled versions.

**Comment by yuval59** [comment]
> I didn't write `pnpm tauri build -b none` for no reason. On windows (and maybe Mac idk), if you don't have the private key, building with bundle will fail with an error. Even if it didn't, if you're building from source, it makes no sense to also make the bundled versions.

Yeah that's fair enough, I'll revert the command thing (tho I do think keeping it as `start-vite` and `build-vite` is a good idea) 

> I also don't think that new markdownlint file is needed.

It's not necessarily needed, but I do think including all the formatting details possible is usually a pretty good thing?
I'm not invested in it, just lmk if you want me to remove it

I'm also adding `tsc --noEmit` to lint:fix

**Comment by franciscoBSalgueiro** [comment]
Yes, I prefer not to have another configuration file. Other than that, looks good to me. Thanks!

**Pull request merged**
