### PR TITLE
Add move tags in the chessboard

### PR DESCRIPTION
**Pull request by franciscoBSalgueiro**

### CODE REVIEW

**Comment by dav1312** [comment]
The circle is sometimes cut and I'm also sometimes getting a weird underline in the moves
Also I don't like the tag itself being text... it looks bad imho
What about an svg?
image

**Comment by franciscoBSalgueiro** [comment]
is this on linux? I could make it an svg.

**Comment by dav1312** [comment]
Yes I'm testing on linux

**Comment by franciscoBSalgueiro** [comment]
Yeah, webkitgtk really sucks compared to the windows and mac native webviews unfortunately.

**Comment by franciscoBSalgueiro** [comment]
please let me know if https://github.com/franciscoBSalgueiro/en-croissant/commit/92a621066d873eb967b6b47cd81ff9470c9313ba helps

**Comment by dav1312** [comment]
> please let me know if [92a6210](https://github.com/franciscoBSalgueiro/en-croissant/commit/92a621066d873eb967b6b47cd81ff9470c9313ba) helps

Looks much better!! 😄 

Perhaps add a _little_ drop shadow too? wdyt? I think it gives it an interesting sense of depth
| image | image |
|---|---|

_This is what I used trying to imitate Lichess but it might not be the best way to do it_
```diff
           <Avatar
             sx={{
               transform: "translateY(-40%) translateX(-50%)",
               zIndex: 100,
+              filter: "url(#shadow)",
+              overflow: "initial"
             }}
             radius="xl"
             color={color}
             variant="filled"
           >
             <svg viewBox="0 0 100 100" width="100%" height="100%">
+              <defs>
+                <filter id="shadow">
+                  <feDropShadow dx="0" dy="1" floodOpacity="0.3" stdDeviation="0"></feDropShadow>
+                </filter>
+              </defs>
               <g>{glyphToSvg[annotation]}</g>
             </svg>
           </Avatar>
```

Also, it looks like the size of the icons is not changing with the board size which can look funny
image

**Comment by franciscoBSalgueiro** [comment]
that shadow looks good thanks!

**Pull request merged**
