### PR TITLE
fix issue #260

### PR DESCRIPTION
**Pull request by topce**
fix issue 260 ui put table upper so we see all pieces
image

### CODE REVIEW

**Comment by franciscoBSalgueiro** [comment]
This is not the way to fix it. Instead of the pieces being cut, it will be the game info. Making that section scrollable would be better.

**Comment by topce** [comment]
Hi @franciscoBSalgueiro 
I do not agree with statement bellow: 
> This is not the way to fix it. Instead of the pieces being cut, it will be the game info. Making that section scrollable would be better.
As you can see from screenshots all information is shown (fit in screen) without need of additional scrollbars
all information from game info is shown nothing is cut, or maybe I missing something?
So from  user experience perspective I think my solution is superior.
It does not force user to use scrollbar to see all peaces .
Also two scrollbars to right hand side looks ugly to me. 

picture speaks a thousand words: 
image

**Comment by franciscoBSalgueiro** [comment]
On that particular screen size it's fine, just as the original was on my screen size, but if you make your app height smaller you'll see that it has the same problem. Either way, the reason it started working on your screen size was because you removed the dividers, the change in board position was unnecessary.

See if my fix works well for you. If you still need to scroll, maybe try changing the font size in settings to 90%

**Comment by topce** [comment]
> On that particular screen size it's fine, just as the original was on my screen size, but if you make your app height smaller you'll see that it has the same problem. Either way, the reason it started working on your screen size was because you removed the dividers, the change in board position was unnecessary.
> 
> If you still need to scroll, maybe try changing the font size in settings to 90%. From your screenshot it looks like the letters are too large.

For me it did not worked when removing dividers, but when move chess board up it worked.
Anyway you tip  for font size is working  .  
Maybe to put it by default to be 90?
For info my laptop (windows 11) all values are recommended.
resolution 1920x1080  
scale  150% 
text size minimum


Thank you for your help and nice chess application!

**Pull request closed without merging**
